export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

/* LOGIN */
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";

/* USUARIO */
export const USUARIO_INGRESO_OK = "USUARIO_INGRESO_OK";
export const USUARIO_INGRESO_ERROR = "USUARIO_INGRESO_ERROR";
export const USUARIO_BUSCAR_OK = "USUARIO_BUSCAR_OK";
export const USUARIO_BUSCAR_ERROR = "USUARIO_BUSCAR_ERROR";
export const DOCENTE_BUSCAR_OK = "DOCENTE_BUSCAR_OK";
export const DOCENTE_BUSCAR_ERROR = "DOCENTE_BUSCAR_ERROR";
export const USUARIO_ELIMINAR_OK = "USUARIO_ELIMINAR_OK";
export const USUARIO_ELIMINAR_ERROR = "USUARIO_ELIMINAR_ERROR";

/* CARRERA */
export const CARRERA_INGRESO_OK = "CARRERA_INGRESO_OK";
export const CARRERA_INGRESO_ERROR = "CARRERA_INGRESO_ERROR";
export const CARRERA_BUSCAR_OK = "CARRERA_BUSCAR_OK";
export const CARRERA_BUSCAR_ERROR = "CARRERA_BUSCAR_ERROR";
export const CARRERA_ELIMINAR_OK = "CARRERA_ELIMINAR_OK";
export const CARRERA_ELIMINAR_ERROR = "CARRERA_ELIMINAR_ERROR";
export const ENVIAR_ASIGNATURA = "ENVIAR_ASIGNATURA";
export const QUITAR_ASIGNATURA = "ENVIAR_ASIGNATURA";

/* PERIODO */
export const PERIODO_INGRESO_OK = "PERIODO_INGRESO_OK";
export const PERIODO_INGRESO_ERROR = "PERIODO_INGRESO_ERROR";
export const PERIODO_BUSCAR_OK = "PERIODO_BUSCAR_OK";
export const PERIODO_BUSCAR_ERROR = "PERIODO_BUSCAR_ERROR";
export const PERIODO_ELIMINAR_OK = "PERIODO_ELIMINAR_OK";
export const PERIODO_ELIMINAR_ERROR = "PERIODO_ELIMINAR_ERROR";
export const PERIODO_ACTIVAR_OK = "PERIODO_ACTIVAR_OK";
export const PERIODO_ACTIVAR_ERROR = "PERIODO_ACTIVAR_ERROR";

/* ASIGNATURA */
export const ASIGNATURA_INGRESO_OK = "ASIGNATURA_INGRESO_OK";
export const ASIGNATURA_INGRESO_ERROR = "ASIGNATURA_INGRESO_ERROR";
export const ASIGNATURA_BUSCAR_OK = "ASIGNATURA_BUSCAR_OK";
export const ASIGNATURA_BUSCAR_ERROR = "ASIGNATURA_BUSCAR_ERROR";
export const ASIGNATURA_ELIMINAR_OK = "ASIGNATURA_ELIMINAR_OK";
export const ASIGNATURA_ELIMINAR_ERROR = "ASIGNATURA_ELIMINAR_ERROR";
export const ASIGNATURA_DOCENTES_OK = "ASIGNATURA_ACTIVAR_OK";
export const ASIGNATURA_DOCENTES_ERROR = "ASIGNATURA_ACTIVAR_ERROR";
export const ASIGNATURAS_COORDINADOR_OK = "ASIGNATURAS_COORDINADOR_OK";
export const ASIGNATURAS_COORDINADOR_ERROR = "ASIGNATURAS_COORDINADOR_ERROR";

/* TEMA */
export const TEMA_INGRESO_OK = "TEMA_INGRESO_OK";
export const TEMA_INGRESO_ERROR = "TEMA_INGRESO_ERROR";
export const TEMA_BUSCAR_OK = "TEMA_BUSCAR_OK";
export const TEMA_BUSCAR_ERROR = "TEMA_BUSCAR_ERROR";
export const TEMA_ELIMINAR_OK = "TEMA_ELIMINAR_OK";
export const TEMA_ELIMINAR_ERROR = "TEMA_ELIMINAR_ERROR";
export const TEMA_PADRE_BUSCAR_OK = "TEMA_PADRE_BUSCAR_OK";
export const TEMA_PADRE_BUSCAR_ERROR = "TEMA_PADRE_BUSCAR_ERROR";

/* REFERENCIA */
export const REFERENCIA_INGRESO_OK = "REFERENCIA_INGRESO_OK";
export const REFERENCIA_INGRESO_ERROR = "REFERENCIA_INGRESO_ERROR";
export const REFERENCIA_BUSCAR_OK = "REFERENCIA_BUSCAR_OK";
export const REFERENCIA_BUSCAR_ERROR = "REFERENCIA_BUSCAR_ERROR";
export const REFERENCIA_ELIMINAR_OK = "REFERENCIA_ELIMINAR_OK";
export const REFERENCIA_ELIMINAR_ERROR = "REFERENCIA_ELIMINAR_ERROR";
export const REFERENCIA_ASIGNATURA_OK = "REFERENCIA_ASIGNATURA_OK";
export const REFERENCIA_ASIGNATURA_ERROR = "REFERENCIA_ASIGNATURA_ERROR";

/* PRACTICA */
export const PRACTICA_INGRESO_OK = "PRACTICA_INGRESO_OK";
export const PRACTICA_INGRESO_ERROR = "PRACTICA_INGRESO_ERROR";
export const PRACTICA_BUSCAR_OK = "PRACTICA_BUSCAR_OK";
export const PRACTICA_BUSCAR_ERROR = "PRACTICA_BUSCAR_ERROR";
export const PRACTICA_ELIMINAR_OK = "PRACTICA_ELIMINAR_OK";
export const PRACTICA_ELIMINAR_ERROR = "PRACTICA_ELIMINAR_ERROR";
export const PRACTICA_ASIG_BUSCAR_OK = "PRACTICA_ASIG_BUSCAR_OK";
export const PRACTICA_ASIG_BUSCAR_ERROR = "PRACTICA_ASIG_BUSCAR_ERROR";
export const PRACTICA_ID_BUSCAR_OK = "PRACTICA_ID_BUSCAR_OK";
export const PRACTICA_ID_BUSCAR_ERROR = "PRACTICA_ID_BUSCAR_ERROR";

export const VACIAR_MENSAJE = "VACIAR_MENSAJE";
export const CARGANDO = "CARGANDO";
