export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";

export const USUARIO_INGRESO_OK = "USUARIO_INGRESO_OK";
export const USUARIO_INGRESO_ERROR = "USUARIO_INGRESO_ERROR";
export const USUARIO_BUSCAR_OK = "USUARIO_BUSCAR_OK";
export const USUARIO_BUSCAR_ERROR = "USUARIO_BUSCAR_ERROR";
export const USUARIO_ELIMINAR_OK = "USUARIO_ELIMINAR_OK";
export const USUARIO_ELIMINAR_ERROR = "USUARIO_ELIMINAR_ERROR";

export const CARRERA_INGRESO_OK = "CARRERA_INGRESO_OK";
export const CARRERA_INGRESO_ERROR = "CARRERA_INGRESO_ERROR";
export const CARRERA_BUSCAR_OK = "CARRERA_BUSCAR_OK";
export const CARRERA_BUSCAR_ERROR = "CARRERA_BUSCAR_ERROR";
export const CARRERA_ELIMINAR_OK = "CARRERA_ELIMINAR_OK";
export const CARRERA_ELIMINAR_ERROR = "CARRERA_ELIMINAR_ERROR";

export const PERIODO_INGRESO_OK = "PERIODO_INGRESO_OK";
export const PERIODO_INGRESO_ERROR = "PERIODO_INGRESO_ERROR";
export const PERIODO_BUSCAR_OK = "PERIODO_BUSCAR_OK";
export const PERIODO_BUSCAR_ERROR = "PERIODO_BUSCAR_ERROR";
export const PERIODO_ELIMINAR_OK = "PERIODO_ELIMINAR_OK";
export const PERIODO_ELIMINAR_ERROR = "PERIODO_ELIMINAR_ERROR";
export const PERIODO_ACTIVAR_OK = "PERIODO_ACTIVAR_OK";
export const PERIODO_ACTIVAR_ERROR = "PERIODO_ACTIVAR_ERROR";

export const VACIAR_MENSAJE = "VACIAR_MENSAJE";
